valhalla/odin

- .gitignore
- Makefile.am
- src/odin/directionsbuilder.cc
- src/odin/maneuversbuilder.cc
- src/odin/streetname.cc
- src/odin/streetnames.cc
- test/sign.cc
- test/streetname.cc
- test/streetnames.cc
- valhalla/odin/streetname.h
- valhalla/odin/streetnames.h
@dnesbitt61 @gknisely @kevinkreiser 
Here are some examples of the improvements:
##########################################
Example#1 - 6 maneuvers collapsed to 1
BEFORE
Turn sharp left onto US 30/Lincoln Highway. | 11.656999 km
Continue onto US 30 West. | 5.005000 km
Continue onto US 30. | 2.397000 km
Continue onto US 30 West. | 2.331000 km
Continue onto US 30/Lincoln Highway. | 3.668000 km
Continue onto Bedford Bypass. | 3.019000 km
AFTER
Turn sharp left onto US 30 West. | 28.077000 km
##########################################
Example#2
BEFORE
Turn left onto East 33rd Street. | 0.155000 km
Continue onto West 33rd Street. | 0.072853 km
AFTER
Turn left onto East 33rd Street. | 0.227853 km
> Added logic to collapse unneeded maneuvers - the maneuvers had only prefix and/or suffix directional differences

- src/odin/maneuver.cc
- src/odin/maneuversbuilder.cc
- src/odin/narrativebuilder.cc
- test/maneuversbuilder.cc
- valhalla/odin/maneuver.h
- valhalla/odin/maneuversbuilder.h
@dnesbitt61 @gknisely @kevinkreiser 
Example:
1: Start out going northwest on MD 24/Vietnam Veterans Memorial Highway. | 0.071404 km
2: Make a left U-turn at Bel Air South Parkway onto MD 24/Vietnam Veterans Memorial Highway. | 0.119695 km
3: You have arrived at your destination. | 0.000000 km
> Added doubly digitized u-turn capability

- src/odin/maneuver.cc
- src/odin/maneuversbuilder.cc
- test/maneuversbuilder.cc
- valhalla/odin/maneuver.h
- valhalla/odin/maneuversbuilder.h
@dnesbitt61 @gknisely @kevinkreiser 
Example #1:
OLD: Make a right U-turn onto Stonewall Shops Square.
NEW: Make a left U-turn onto Stonewall Shops Square.
Example #2:
OLD: Make a right U-turn at Moravia Park Drive onto US 40 West/Pulaski Highway.
NEW: Make a left U-turn at Moravia Park Drive onto US 40 West/Pulaski Highway.
> Fixed invalid u-turn direction

- .gitignore
- Makefile.am
- circle.yml
- configure.ac
- m4/ax_boost_thread.m4
- scripts/install_service_deps.sh
- src/odin/odin_service.cc
- src/odin/service.cc
- valhalla/odin/service.h
two things are added here, a binary that makes use of the odin service layer code, and the odin service layer code with is part of the odin library. it makes use of all the prime_server zmq deps but its part of the library so the simple server in tyr can just use it. this way the same code will be run regardless of in production or testing on our local machines
for odin it was really straight forward, grab some info out of the request that thor passes on to us (hopefully narrative options etc). recontitute the trip_path protobuf from bytes, make directions protobuf, serialize the protobuf bytes (and the original request) onto tyr.
> first draft of odin service layer

- src/odin/maneuver.cc
- src/odin/maneuversbuilder.cc
- src/odin/narrativebuilder.cc
- valhalla/odin/maneuver.h
- valhalla/odin/maneuversbuilder.h
- valhalla/odin/narrativebuilder.h
Added narrative for TripDirections_Maneuver_Type_kStayStraight, TripDirections_Maneuver_Type_kStayRight, and TripDirections_Maneuver_Type_kStayLeft maneuver types
BEFORE
Continue on I 895 South/Harbor Tunnel Thruway.
AFTER
Keep right to take exit 62 onto I 895 South/Harbor Tunnel Thruway toward Annapolis.
> Added fork functionality to maneuver

- src/odin/maneuversbuilder.cc
- src/odin/narrativebuilder.cc
EXAMPLE#1
BEFORE
Turn left onto PA 741.
AFTER
Turn left onto Rohrerstown Road/PA 741. Continue on PA 741.
EXAMPLE#2
BEFORE
Turn right onto VA 7.
AFTER
Turn right onto VA 7/Leesburg Pike. Continue on VA 7.
> Added logic to set and display the maneuver begin street name(s) when needed

- src/odin/directionsbuilder.cc
- src/odin/maneuver.cc
- src/odin/narrativebuilder.cc
- valhalla/odin/maneuver.h
- valhalla/odin/narrativebuilder.h
Example:
2: Turn right onto North Prince Street/US 222. Continue on US 222. | 3.9 mi
VERBAL_ALERT: Turn right onto North Prince Street.
VERBAL_PRE: Turn right onto North Prince Street,US 222.
VERBAL_POST: Continue on US 222 for 3.9 miles.
> Added verbal instructions for simple turn maneuvers

- src/odin/maneuversbuilder.cc
Fixes #128 
BEFORE
1: Go east. | 0.2 mi
2: Continue. | 0.0 mi
3: Continue. | 0.0 mi
4: Continue. | 0.0 mi
5: Continue. | 0.0 mi
6: Continue. | 0.0 mi
7: Bear right. | 0.1 mi
8: Continue. | 0.0 mi
9: Continue. | 0.0 mi
10: Bear right. | 0.0 mi
11: Bear right. | 0.1 mi
12: Continue. | 0.1 mi
13: Turn right. | 0.0 mi
14: Bear left. | 0.0 mi
15: Continue. | 0.0 mi
16: Bear left. | 0.0 mi
17: Bear right. | 0.0 mi
18: Bear left. | 0.0 mi
19: Continue. | 0.0 mi
20: Bear left. | 0.0 mi
21: Bear right. | 0.0 mi
22: Continue. | 0.0 mi
23: Continue. | 0.0 mi
24: Continue. | 0.0 mi
25: Enter the roundabout and take the 1st exit. | 0.0 mi
26: Exit the roundabout. | 0.0 mi
27: Bear right. | 0.0 mi
28: Continue. | 0.0 mi
29: You have arrived at your destination. | 0.0 mi
AFTER
1: Go east. | 0.8 mi
2: …
> Combine unnamed edges to fix #128

- src/odin/narrativebuilder.cc
- valhalla/odin/narrativebuilder.h
cc @ecgreb
START MANEUVER BEFORE
VERBAL_PRE: Go southwest on West Chocolate Avenue, U.S. 4 22.
VERBAL_POST: Continue for 6 tenths of a mile.
START MANEUVER AFTER
VERBAL_PRE: Go southwest on West Chocolate Avenue, U.S. 4 22 for 6 tenths of a mile.
CONTINUE MANEUVER BEFORE
VERBAL_PRE: Continue on U.S. 3 22 West.
VERBAL_POST: Continue for 6.8 miles.
CONTINUE MANEUVER AFTER
VERBAL_PRE: Continue on U.S. 3 22 West for 6.8 miles.
> Update the verbal intructions for the start and continue maneuver types so app will be less chatty

- src/odin/maneuversbuilder.cc
fixes valhalla/mjolnir#311
maneuvers": [
{
"begin_shape_index": 0,
"length": 5.347,
"time": 165,
"type": 1,
"end_shape_index": 89,
"instruction": "Go north on AS-I.",
"verbal_pre_transition_instruction": "Go north on AS-I for 5.3 kilometers.",
"street_names": 
[
"AS-I"
]
},
> Fixes missing 'time' value for first 'maneuver'

- src/odin/narrativebuilder.cc
- test/narrativebuilder.cc
BEFORE
Go south on Stone Road.
AFTER
Head south on Stone Road.
> Changed "Go" to "Head" for the following instructions: Start, ExitFerry, and PostTransitConnectionDestination

- src/odin/enhancedtrippath.cc
- src/odin/maneuver.cc
- src/odin/maneuversbuilder.cc
- src/odin/narrativebuilder.cc
- valhalla/odin/enhancedtrippath.h
- valhalla/odin/maneuver.h
- valhalla/odin/narrativebuilder.h
closed #158 
**Walkway example:**
BEFORE
Turn right.
AFTER
Turn right onto walkway.
**Cycleway example:**
BEFORE
Turn left.
AFTER
Turn left onto cycleway.
**Mountain bike trail example:**
BEFORE
Head west.
AFTER
Head west on mountain bike trail.
> Improved narrative for unnamed walkway, cycleway, and mountain bike trail

- src/odin/maneuversbuilder.cc
- valhalla/odin/maneuversbuilder.h
There we will not call out to enter or exit a simple stop such as a bus stop
> Collapse the TransitConnectionStart and TransitConnectionDestination Maneuvers if the corresponding stop is not a station

- proto/directions_options.proto
- src/odin/directionsbuilder.cc
- src/odin/enhancedtrippath.cc
- src/odin/util.cc
- valhalla/odin/enhancedtrippath.h
Closes #171 
Added "narrative" flag to directions_options to allow users to disable narrative production. Locations, shape, length, and time are still returned.
The narrative production is enabled by default.
Example:
http://localhost:8002/route?json={"locations":[{"lat":39.287403,"lon":-76.615128,"street":"South Charles Street"},{"lat":39.537704,"lon":-76.351112,"street":"North Main Street"}],"costing":"auto","directions_options":{"units":"miles","narrative":false}}
> Added ability to disable narrative production.

- proto/tripdirections.proto
- src/odin/directionsbuilder.cc
- src/odin/maneuver.cc
- src/odin/maneuversbuilder.cc
- src/odin/narrativebuilder.cc
- test/maneuversbuilder.cc
- test/narrativebuilder.cc
- valhalla/odin/maneuver.h
- valhalla/odin/maneuversbuilder.h
- valhalla/odin/narrativebuilder.h
Fixes #176 
Appends the verbal pre-transition instruction of a short (by time) maneuver with the verbal transition alert instruction of the next maneuver
BEFORE
AFTER
> Added verbal multi-cue capability

- src/odin/maneuversbuilder.cc
```
BEFORE
5: Transfer at the 6 Av station. | 0.0 mi
AFTER
5: Exit the 14th Street station. | 0.0 mi
6: Enter the 6 Av station. | 0.0 mi
```
> Do not combine transit connection edges

- locales/en-US.json
- src/odin/directionsbuilder.cc
- src/odin/maneuver.cc
- src/odin/narrativebuilder.cc
- src/odin/transitstop.cc
- test/narrativebuilder.cc
- valhalla/odin/narrative_dictionary.h
- valhalla/odin/transitstop.h
this should have all of the transit stuff using the dictionary/phrases now instead of hardcoded strings. obviously its not tested until i can merge @dgearhart 's tests, so as soon as he pushes/generates those i'll pull them and fix anything ive messed up.
> remove hardcoded transit narrative strings and use phrasesets

- locales/de-DE.json
- src/odin/util.cc
- test/util.cc
- valhalla/odin/util.h
this works really nice in that it tells both what and where the problem is. i tested missing phrases, missing replacements, missing tags, wrong names of phrases (wrong keys), wrong items under the instruction, and if the posix locale is supported. only thing i dont like is that its a unit test. id rather it be run in make and fail compilation instead but this is probably too strict anyway.
oh also it found a bug in german language file
@dgearhart please have a look
> validate language files against en-US

- locales/cs-CZ.json
- locales/de-DE.json
- locales/en-US.json
- src/odin/narrative_dictionary.cc
- src/odin/narrativebuilder.cc
- test/narrative_dictionary.cc
- test/narrativebuilder.cc
- valhalla/odin/narrative_dictionary.h
- valhalla/odin/narrativebuilder.h
Added empty_transit_name_labels to the following phrase sets:
- transit
- transit_verbal
- transit_remain_on
- transit_remain_on_verbal
- transit_transfer
- transit_transfer_verbal
Added some example_phrases too.
@mormegil-cz could you please update cs-CZ.json
@kevinkreiser could you please update de-DE.json
Closes #269
> Added empty_transit_name_labels with some examples

- locales/cs-CZ.json
Translated cs-CZ localization for the new messages introduced in #289.
> Added Czech localization for new empty_transit_name_labels

- locales/de-DE.json
basically because we cant gaurantee a named line will be there we have to do the sucky compromise of taking out the word for `line`. this reads very clunky but there is no way to do it without adding more phrases.
actually that might be a good strategy for all of this stuff. have the phrases once with the replacement from the data, but then have them again with the replacement from the replacements list. decoupling them would allow for much better sounding translations.
> german updates

- src/odin/maneuversbuilder.cc
Closes #165 
Closes #155 
For this example route:
http://www.openstreetmap.org/directions?engine=mapzen_car&route=28.5669%2C77.2078%3B28.6168%2C77.3647#map=12/28.5906/77.2856
Here is the before and after comparison:
```
BEFORE
17: Continue. | 1.6 mi
18: Continue. | 0.4 mi
19: Continue. | 0.8 mi
AFTER
17: Continue. | 2.8 mi
BEFORE
23: Continue. | 0.2 mi
24: Continue. | 0.1 mi
25: Continue. | 0.4 mi
26: Turn left. | 0.3 mi
27: Bear right. | 0.2 mi
28: Turn right. | 0.1 mi
29: Bear left. | 0.0 mi
30: Your destination is on the left. | 0.0 mi
AFTER
21: Turn left. | 0.4 mi
22: Turn right. | 0.1 mi
23: Your destination is on the left. | 0.0 mi
```
Removed 7 unneeded maneuvers from the above example
> Combine unnamed straight maneuvers

- src/odin/maneuversbuilder.cc
Both the previous edge and the current edge must be marked as highways in order to ignore within the intersecting forward edge method.
Closes #292 
```
BEFORE
1: Drive southwest on Church Avenue/NY 27. Continue on NY 27 West. | 0.1 mi
2: You have arrived at NY 27 West. | 0.0 mi
AFTER
1: Drive southwest on Church Avenue/NY 27. | 0.0 mi
2: Turn right onto NY 27 West/Prospect Expressway. | 0.1 mi
3: You have arrived at NY 27 West. | 0.0 mi
```
> Updated intersecting forward edge logic

- locales/make_locales.sh
`localedef` syntax is different on OSX, looks like this is used for debugging only, so just skipping it on darwin
ps. not messing with `sed` this time - easier to install `gsed` locally, otherwise expressions become too gnarly :)
> only generate locales on linux

- .gitignore
- locales/cs-CZ.json
- locales/de-DE.json
- locales/en-US.json
- locales/it-IT.json
- locales/make_locales.sh
- scripts/dependencies.sh
- src/odin/narrative_dictionary.cc
- src/odin/narrativebuilder.cc
- src/odin/util.cc
- test/util_odin.cc
this also ~~avoids testing locales we never use and~~ uses the more standard charmap name that `localedef` uses
it fixes an issue in which the wrong locale was being used to test at different points
> use integers to avoid precision issues

- locales/cs-CZ.json
- locales/de-DE.json
- locales/en-US.json
- locales/fr-FR.json
- locales/it-IT.json
- src/odin/narrative_builder_factory.cc
- src/odin/util.cc
- test/narrative_dictionary.cc
- test/narrativebuilder.cc
- test/util_odin.cc
- valhalla/odin/util.h
this allows requests to specify language aliases instead of the `bcp47` codes we've been adhering too. it does so by adding an `aliases` section to the json of a particular file. this means we can quickly look up a language and we dont have to duplicate it or the object its parsed into (`shared_ptr`). it also allows us to match many different standards (whatever those may be). in fact maybe we should put the 3 letter codes in here as well?
another important thing here is that if a language file cant load, because the json is broken or an alias clashes with another language file, we will throw an exception that is not handled and abort. this makes sure that our tests fail when they should. before we were doing a `LOG_WARN` when this was happening which could technically leave us with no …
> allow language aliases to satisfy different naming schemes

- Makefile.am
pushd/popd is available in bash, but not in POSIX. Some shells, like OpenBSD’s ksh, don’t provide them.
> For portability, use cd foo && cd - instead of pushd foo && popd.

- locales/make_locales.sh
`localedef` does not work on OSX, so run it after header generation (otherwise header is not generated due to `set -e`)
> install test locales after code generation

- src/odin/narrativebuilder.cc
- test/narrativebuilder.cc
Closes #351 
``` Diff
< BEFORE
<    VERBAL_ALERT: Enter the roundabout.
> AFTER
>    VERBAL_ALERT: Enter the roundabout and take the 3rd exit.
```
``` Diff
< BEFORE
<    VERBAL_ALERT: Enter the roundabout.
> AFTER
>    VERBAL_ALERT: Enter the roundabout and take the 2nd exit.
```
> Updated the 'enter roundabout' verbal alert to have spoke count

- src/odin/maneuversbuilder.cc
It possible to get a straight "turn channel", if link reclassification is disabled and link_type is explicitly set to "slip"
> combine straight turn channel

- src/odin/maneuversbuilder.cc
@randymeech - fixed, thanks for submitting
``` Diff
< BEFORE
< 4: Turn left onto East Orange Street. | 0.5 mi
> AFTER
> 4: Turn right onto North Broad Street/PA 462 West. | 0.1 mi
> 5: Turn left onto East Orange Street. | 0.5 mi
```
> Fixed missing turn by updating the forward intersecting edge logic.
