valhalla/odin

- proto/trippath.proto
- src/odin/narrativebuilder.cc
- valhalla/odin/narrativebuilder.h
> Removed leg from TripPath and added simple narrative logic for end to end test

- Makefile.am
- proto/tripdirections.proto
- src/odin/directionsbuilder.cc
- src/odin/maneuversbuilder.cc
- src/odin/narrativebuilder.cc
- valhalla/odin/directionsbuilder.h
- valhalla/odin/maneuversbuilder.h
- valhalla/odin/narrativebuilder.h
Added skeleton code for builders
Added total distance for simple output
> Added initial odin output interface: tripdirections.proto

- src/odin/directionsbuilder.cc
- valhalla/odin/directionsbuilder.h
> Updated to return TripDirections

- Makefile.am
- proto/tripdirections.proto
- proto/trippath.proto
- src/odin/directionsbuilder.cc
- src/odin/enhancedtrippath.cc
- src/odin/maneuver.cc
- src/odin/maneuversbuilder.cc
- src/odin/streetname.cc
- src/odin/streetnames.cc
- valhalla/odin/directionsbuilder.h
- valhalla/odin/enhancedtrippath.h
- valhalla/odin/maneuver.h
- valhalla/odin/maneuversbuilder.h
- valhalla/odin/streetname.h
- valhalla/odin/streetnames.h
basic skeleton
needs comments, tests, and more logic
depends on midgard
> Initial maneuver creation code

- .gitignore
- Makefile.am
- src/odin/maneuversbuilder.cc
- test/maneuversbuilder.cc
- valhalla/odin/maneuversbuilder.h
> add ManeuversBuilder::SetSimpleDirectionalManeuverType and tests

- proto/trippath.proto
- src/odin/directionsbuilder.cc
- src/odin/maneuver.cc
- src/odin/maneuversbuilder.cc
- src/odin/narrativebuilder.cc
- test/maneuversbuilder.cc
- valhalla/odin/directionsbuilder.h
- valhalla/odin/maneuver.h
- valhalla/odin/maneuversbuilder.h
- valhalla/odin/narrativebuilder.h
- valhalla/odin/streetnames.h
> Improved capabilty for quick skeleton narrative

- src/odin/maneuver.cc
- src/odin/maneuversbuilder.cc
- src/odin/narrativebuilder.cc
- src/odin/streetnames.cc
- valhalla/odin/maneuver.h
- valhalla/odin/streetnames.h
> Reduced maneuvers by using common street name logic

- proto/tripdirections.proto
- proto/trippath.proto
- src/odin/enhancedtrippath.cc
- src/odin/maneuver.cc
- src/odin/maneuversbuilder.cc
- src/odin/narrativebuilder.cc
- valhalla/odin/enhancedtrippath.h
- valhalla/odin/maneuver.h
- valhalla/odin/narrativebuilder.h
- valhalla/odin/streetnames.h
> Added basic functionality for the following: ramp, exit, stay, merge, roundabout, and ferry

- src/odin/narrativebuilder.cc
> fixed left turns

- proto/trippath.proto
- src/odin/enhancedtrippath.cc
- src/odin/maneuversbuilder.cc
- valhalla/odin/enhancedtrippath.h
@gknisely @dnesbitt61 @kevinkreiser
> Road class updates and Added EnhancedTripPath_Node

- proto/trippath.proto
> fixed value

- src/odin/enhancedtrippath.cc
- src/odin/maneuversbuilder.cc
>  Added more debug info to help with test creation

- proto/trippath.proto
@gknisely @dnesbitt61 @kevinkreiser
> Made exit name a repeated field

- proto/trippath.proto
- src/odin/enhancedtrippath.cc
@gknisely @dnesbitt61 @kevinkreiser
> Made Exit optional and Added exit trace info

- src/odin/maneuver.cc
- src/odin/maneuversbuilder.cc
- src/odin/narrativebuilder.cc
- valhalla/odin/maneuver.h
- valhalla/odin/maneuversbuilder.h
- valhalla/odin/narrativebuilder.h
> Added RelativeDirection and Added straight/right/left for ramps

- src/odin/narrativebuilder.cc
- valhalla/odin/narrativebuilder.h
> Added FormExitRightInstruction and FormExitLeftInstruction

- .gitignore
- Makefile.am
- src/odin/enhancedtrippath.cc
- src/odin/maneuversbuilder.cc
- test/enhancedtrippath.cc
- test/maneuversbuilder.cc
- valhalla/odin/enhancedtrippath.h
- valhalla/odin/maneuversbuilder.h
Added enhancedtrippath tests
Added DetermineRelativeDirection tests
> Found and fixed IsSimilarTurnDegree bug

- .gitignore
- Makefile.am
- src/odin/maneuversbuilder.cc
- src/odin/sign.cc
- test/sign.cc
- valhalla/odin/maneuver.h
- valhalla/odin/sign.h
> Added odin::Sign and associated tests

- proto/trippath.proto
- src/odin/enhancedtrippath.cc
- src/odin/maneuver.cc
> Updates to switch Exit to Sign

- Makefile.am
- proto/trippath.proto
- src/odin/enhancedtrippath.cc
- src/odin/maneuver.cc
- src/odin/maneuversbuilder.cc
- src/odin/narrativebuilder.cc
- src/odin/sign.cc
- src/odin/signs.cc
- test/sign.cc
- valhalla/odin/maneuver.h
- valhalla/odin/sign.h
- valhalla/odin/signs.h
> Added initial exit sign capability

- src/odin/narrativebuilder.cc
> Added left exit sign info

- src/odin/maneuversbuilder.cc
- src/odin/narrativebuilder.cc
> Gdg 	Added ramp right and left exit info

- src/odin/maneuversbuilder.cc
- src/odin/narrativebuilder.cc
> Added straight ramp exit info

- src/odin/narrativebuilder.cc
> Added limited use of sign name for exits and ramps

- .gitignore
- Makefile.am
- src/odin/narrativebuilder.cc
- test/narrativebuilder.cc
> Added tests for ramp and exit maneuvers

- proto/trippath.proto
- src/odin/enhancedtrippath.cc
> Switched name to internal_intersection

- src/odin/maneuver.cc
- src/odin/maneuversbuilder.cc
- src/odin/narrativebuilder.cc
- test/maneuversbuilder.cc
- valhalla/odin/maneuver.h
- valhalla/odin/maneuversbuilder.h
> Added internal_intersection support

- Makefile.am
- src/odin/enhancedtrippath.cc
- src/odin/maneuver.cc
- src/odin/maneuversbuilder.cc
- src/odin/sign.cc
- src/odin/signs.cc
- src/odin/streetnames.cc
- src/odin/util.cc
- test/maneuversbuilder.cc
- valhalla/odin/enhancedtrippath.h
- valhalla/odin/maneuver.h
- valhalla/odin/sign.h
- valhalla/odin/signs.h
- valhalla/odin/streetnames.h
- valhalla/odin/util.h
> Added ManeuverBuilder::Combine internal intersection unit tests

- proto/trippath.proto
- src/odin/enhancedtrippath.cc
- src/odin/util.cc
- test/enhancedtrippath.cc
- valhalla/odin/enhancedtrippath.h
- valhalla/odin/util.h
refactoroid to fix corruption issue
> added gate, toll_booth, and accepted_payment

- src/odin/enhancedtrippath.cc
- src/odin/maneuversbuilder.cc
- valhalla/odin/enhancedtrippath.h
> Added node trace string

- proto/trippath.proto
- src/odin/enhancedtrippath.cc
- src/odin/maneuversbuilder.cc
Also - removed accepted_payment
@gknisely @dnesbitt61 @kevinkreiser
> Added route request debug string - therefore, we can use p-n-c routes to populate our route request test files

- src/odin/maneuversbuilder.cc
- test/maneuversbuilder.cc
> Turn::GetType updates

- proto/trippath.proto
- test/maneuversbuilder.cc
(separate Tertiary and Unclassified)
> Change road classes to be same as in baldr 

- src/odin/maneuver.cc
- src/odin/maneuversbuilder.cc
- valhalla/odin/maneuver.h
- valhalla/odin/maneuversbuilder.h
The following demonstrates the improvments:
THEN
Turn slight right. | 0.142000 km
Continue onto Perry Hall Boulevard. | 0.065867 km
NOW
Turn right onto Perry Hall Boulevard. | 0.207867 km
> Added logic to process simple turn channels

- test/maneuversbuilder.cc
> Added SimpleRightTurnChannelCombine test

- proto/trippath.proto
> Added IntersectingEdge

- proto/trippath.proto
- src/odin/directionsbuilder.cc
- src/odin/enhancedtrippath.cc
- src/odin/maneuversbuilder.cc
- test/enhancedtrippath.cc
- test/maneuversbuilder.cc
- valhalla/odin/directionsbuilder.h
- valhalla/odin/enhancedtrippath.h
> Updated logic to use TripPath_IntersectingEdge

- src/odin/narrativebuilder.cc
> updated continue phrase

- proto/tripdirections.proto
- src/odin/maneuversbuilder.cc
> Fixed improper combining of ramps with other maneuvers

- proto/trippath.proto
paired with @gknisely 
@dnesbitt61 @kevinkreiser
> updated location

- proto/tripdirections.proto
- src/odin/directionsbuilder.cc
- valhalla/odin/directionsbuilder.h
Added assignments in the DirectionsBuilder
> Added locations to the TripDirections PBF

- proto/tripdirections.proto
- proto/trippath.proto
- src/odin/directionsbuilder.cc
> Changed StopType to Type under Location

- src/odin/directionsbuilder.cc
> Updated location assignments

- Makefile.am
- proto/directions_options.proto
- proto/tripdirections.proto
- src/odin/directionsbuilder.cc
- src/odin/enhancedtrippath.cc
- src/odin/maneuversbuilder.cc
- src/odin/narrativebuilder.cc
- src/odin/util.cc
- test/maneuversbuilder.cc
- valhalla/odin/directionsbuilder.h
- valhalla/odin/enhancedtrippath.h
- valhalla/odin/maneuversbuilder.h
- valhalla/odin/narrativebuilder.h
- valhalla/odin/util.h
> Added DirectionsOptions

- src/odin/directionsbuilder.cc
> populated summary length and time

- src/odin/maneuversbuilder.cc
- valhalla/odin/maneuversbuilder.h
BEFORE
Take exit 67A-B on the right onto US 22 East/PA 230 East/US 22 West/US 322 West/Cameron Street toward Harrisburg/Lewistown/State College.
Take exit 67B on the right onto US 22 West/US 322 West toward Lewistown/State College.
Merge onto US 322 West.
AFTER
Take exit 67A-B on the right onto US 322 West/US 22 West/US 22 East/PA 230 East/Cameron Street toward Lewistown/State College/Harrisburg.
Take exit 67B on the right onto US 322 West/US 22 West toward Lewistown/State College.
Merge onto US 322 West.
> Added capability to count and sort consecutive exit signs.

- src/odin/service.cc
requires prime_server reinstall
> small change for primeserver logging

- proto/trippath.proto
> fixed type for: arrival_date_time and departure_date_time

- src/odin/narrativebuilder.cc
- valhalla/odin/narrativebuilder.h
BEFORE
Turn slight right onto Benfield Boulevard.
AFTER
Bear right onto Benfield Boulevard.
> Switched 'slight turns' to 'bear'

- Makefile.am
- proto/tripdirections.proto
- proto/trippath.proto
- src/odin/maneuver.cc
- src/odin/maneuversbuilder.cc
- src/odin/narrativebuilder.cc
- src/odin/transitinfo.cc
- src/odin/transitstop.cc
- valhalla/odin/maneuver.h
- valhalla/odin/narrativebuilder.h
- valhalla/odin/transitinfo.h
- valhalla/odin/transitstop.h
Here is initial example - we can polish this week:
2: Turn right onto 35th Avenue. | 0.1 mi
3: Enter station. | 0.0 mi
4: DEPART: 2015-07-01T08:26 - Take the Dublin/Pleasanton - Daly City toward Daly City. ARRIVE: 2015-07-01T08:47. | 11.4 mi
5: Exit station. | 0.1 mi
6: Go southwest on Market Street. | 0.1 mi
> Transit narrative

- src/odin/maneuver.cc
- src/odin/maneuversbuilder.cc
- src/odin/narrativebuilder.cc
- valhalla/odin/maneuver.h
3: Enter the 34 St - Herald Sq station. | 0.0 mi
4: DEPART: 2015-07-01T08:13 - Take the N toward CONEY ISLAND - STILLWELL AV. ARRIVE: 2015-07-01T08:19. | 1.4 mi
5: Exit the 8 St - NYU station. | 0.0 mi
> Added transit connection stop name logic

- src/odin/maneuver.cc
BEFORE:
DEPART: 2015-07-01T08:13 from 34 St - Herald Sq. Take the N toward CONEY ISLAND - STILLWELL AV. (4 stops). ARRIVE: 2015-07-01T08:19 at 8 St - NYU.
AFTER:
DEPART: 8:13 AM from 34 St - Herald Sq. Take the N toward CONEY ISLAND - STILLWELL AV. (4 stops). ARRIVE: 8:19 AM at 8 St - NYU.
> Updated to use datetime format

- src/odin/enhancedtrippath.cc
- src/odin/maneuver.cc
- src/odin/maneuversbuilder.cc
- src/odin/narrativebuilder.cc
- valhalla/odin/enhancedtrippath.h
- valhalla/odin/maneuver.h
- valhalla/odin/narrativebuilder.h
BEFORE
Keep left to take I 95 South toward Baltimore.
AFTER
Keep left to stay on I 95 South toward Baltimore.
> Enhanced fork maneuvers to call out "to stay on" when appropriate

- src/odin/enhancedtrippath.cc
- src/odin/maneuversbuilder.cc
- src/odin/narrativebuilder.cc
- valhalla/odin/maneuversbuilder.h
- valhalla/odin/narrativebuilder.h
BEFORE
Continue on Vine Street.
AFTER
Middletown Road becomes Vine Street.
> Added "becomes" maneuver functionality

- src/odin/narrativebuilder.cc
- valhalla/odin/narrativebuilder.h
Added verbal constants
Added space to verbal delim
> Added FormVerbalAlertTurnInstruction method

- src/odin/narrativebuilder.cc
- valhalla/odin/narrativebuilder.h
Refactored FormMergeInstruction
Added FormVerbalAlertMergeInstruction and FormVerbalMergeInstruction
> Add verbal merge instruction

- src/odin/narrativebuilder.cc
- valhalla/odin/narrativebuilder.h
Updated FormEnterRoundaboutInstruction, FormExitRoundaboutInstruction, FormEnterFerryInstruction, and FormExitFerryInstruction
Added verbal methods associated with the above
> Added verbal instructions for roundabouts and ferries

- src/odin/narrativebuilder.cc
- test/narrativebuilder.cc
BEFORE
Continue for 1.0 miles.
AFTER
Continue for 1 mile.
BEFORE
Continue for 0.5 miles.
AFTER
Continue for a half mile.
BEFORE
Continue for 0.2 miles.
AFTER
Continue for 2 tenths of a mile.
BEFORE
Continue for 0.1 miles.
AFTER
Continue for 1 tenth of a mile.
BEFORE
Continue for 0.0 miles.
AFTER
Continue for 200 feet.
BEFORE
Continue for 0.0 miles.
AFTER
Continue for 60 feet.
> Added the verbal phrases for smaller distances.

- src/odin/maneuver.cc
- src/odin/maneuversbuilder.cc
- valhalla/odin/maneuver.h
- valhalla/odin/maneuversbuilder.h
BEFORE
Turn left onto Sunstone Drive.
AFTER
Turn left onto Sunstone Drive.
Turn left to stay on Sunstone Drive.
> Added 'T' intersection logic

- src/odin/enhancedtrippath.cc
- valhalla/odin/enhancedtrippath.h
will investigate further in the future to improve logic
Fix for #134
> Added quick fix for improper turn

- proto/tripdirections.proto
- proto/trippath.proto
- src/odin/enhancedtrippath.cc
- src/odin/maneuversbuilder.cc
- test/enhancedtrippath.cc
- test/maneuversbuilder.cc
- valhalla/odin/enhancedtrippath.h
Added cyclability and walkability to IntersectingEdge
@rmglennon this fixes the cycleway roundabout exit count
> Traversability updates

- proto/tripdirections.proto
- proto/trippath.proto
- src/odin/directionsbuilder.cc
- src/odin/enhancedtrippath.cc
- src/odin/maneuversbuilder.cc
- src/odin/narrativebuilder.cc
- valhalla/odin/enhancedtrippath.h
- valhalla/odin/narrativebuilder.h
Added logic so the start and destination maneuver types will be set based on side of street.
Added logic to use side of street in the narrative.
BEFORE
You have arrived at your destination. 
VERBAL_ALERT: You will arrive at your destination.
VERBAL_PRE: You have arrived at your destination.
AFTER
854 7th Avenue is on the right.
VERBAL_ALERT: 8 54 7th Avenue will be on the right.
VERBAL_PRE: 8 54 7th Avenue is on the right.
@ecgreb FYI
> Added side of street to trip path and trip directions.

- src/odin/maneuversbuilder.cc
BEFORE
Stay straight to take the ramp toward Business District.
AFTER
Take the ramp on the left toward Business District.
> Updated DetermineRelativeDirection logic

- src/odin/maneuversbuilder.cc
fixes valhalla/mjolnir#310
1: Go southwest on AS-I/Autovía Mieres - Gijón (Autovía Minera). | 0.3 km
VERBAL_PRE: Go southwest on AS-I, Autovía Mieres - Gijón (Autovía Minera) for 300 meters.
2: Take exit 9 on the right toward AS-116 Olloniego/ AS-117 Langreo. | 0.4 km
VERBAL_ALERT: Take exit 9 on the right.
VERBAL_PRE: Take exit 9 on the right toward AS-1 16 Olloniego,  AS-1 17 Langreo.
3: Enter the roundabout and take the 3rd exit. | 0.2 km
VERBAL_ALERT: Enter roundabout.
VERBAL_PRE: Enter the roundabout and take the 3rd exit.
4: Exit the roundabout onto AS-117/Enlace de Riaño. | 0.1 km
VERBAL_PRE: Exit the roundabout onto AS-1 17, Enlace de Riaño.
VERBAL_POST: Continue for 70 meters.
> Updated to callout roundabouts when edges are also marked as *_link

- locales/en-US.json
- src/odin/narrative_dictionary.cc
- src/odin/narrativebuilder.cc
- test/narrative_dictionary.cc
- valhalla/odin/narrative_dictionary.h
- valhalla/odin/narrativebuilder.h
> Updated ‘slight right and slight left maneuvers’ for guidance g11n

- locales/en-US.json
- src/odin/narrative_dictionary.cc
- src/odin/narrativebuilder.cc
- test/narrative_dictionary.cc
- test/narrativebuilder.cc
- valhalla/odin/narrative_dictionary.h
- valhalla/odin/narrativebuilder.h
> Updated ‘right, sharp right, sharp left, and left maneuvers’ for guidance g11n

- configure.ac
- scripts/install_service_deps.sh
locked prime_server version to 0.3.2; currently not logging long requests
> Do Not Track - Conditional Logging

- locales/en-US.json
- src/odin/narrative_dictionary.cc
- src/odin/narrativebuilder.cc
- test/narrative_dictionary.cc
- valhalla/odin/narrative_dictionary.h
> Updated ‘u-turn right and u-turn left maneuvers’ for guidance g11n

- src/odin/narrativebuilder.cc
> Only create verbal alert instruction for 'Merge maneuver' if previous maneuver is > 1.5 km

- locales/en-US.json
- src/odin/narrative_dictionary.cc
- src/odin/narrativebuilder.cc
- test/narrative_dictionary.cc
- test/narrativebuilder.cc
- valhalla/odin/narrative_dictionary.h
> Updated ‘ramp straight maneuver’ for guidance g11n

- locales/en-US.json
- src/odin/narrative_dictionary.cc
- src/odin/narrativebuilder.cc
- test/narrative_dictionary.cc
- test/narrativebuilder.cc
- valhalla/odin/narrative_dictionary.h
> Updated ‘ramp right and ramp left maneuvers’ for guidance g11n

- locales/en-US.json
- src/odin/narrative_builder_factory.cc
- src/odin/narrative_dictionary.cc
- src/odin/narrativebuilder.cc
- test/narrative_dictionary.cc
- test/narrativebuilder.cc
- valhalla/odin/narrative_dictionary.h
- valhalla/odin/narrativebuilder.h
> Updated ‘exit right and exit left maneuvers’ for guidance g11n

- proto/tripdirections.proto
- src/odin/directionsbuilder.cc
- src/odin/maneuversbuilder.cc
- valhalla/odin/directionsbuilder.h
- valhalla/odin/transitrouteinfo.h
> Added transit type to trip directions

- src/odin/narrative_builder_factory.cc
- src/odin/service.cc
closes #241 
thanks @kevinkreiser for the service help
> Set language to default (en-US) if the language option is missing or is not supported

- locales/en-US.json
- src/odin/narrative_dictionary.cc
- src/odin/narrativebuilder.cc
- test/narrative_dictionary.cc
- test/narrativebuilder.cc
- valhalla/odin/narrative_dictionary.h
- valhalla/odin/narrativebuilder.h
> Updated ‘stay straight, stay right, and stay left maneuvers’ for guidance g11n

- locales/en-US.json
- src/odin/narrative_dictionary.cc
- src/odin/narrativebuilder.cc
- test/narrative_dictionary.cc
- test/narrativebuilder.cc
- valhalla/odin/narrative_dictionary.h
- valhalla/odin/narrativebuilder.h
> Updated ‘merge maneuver’ for guidance g11n

- locales/en-US.json
- src/odin/narrative_dictionary.cc
- src/odin/narrativebuilder.cc
- test/narrative_dictionary.cc
- test/narrativebuilder.cc
- valhalla/odin/narrative_dictionary.h
- valhalla/odin/narrativebuilder.h
> Updated ‘roundabout enter maneuver’ for guidance g11n

- locales/en-US.json
- src/odin/narrative_dictionary.cc
- src/odin/narrativebuilder.cc
- test/narrative_dictionary.cc
- test/narrativebuilder.cc
- valhalla/odin/narrative_dictionary.h
> Updated ‘roundabout exit maneuver’ for guidance g11n

- locales/en-US.json
- test/narrativebuilder.cc
> Added example phrases to use with translation tool

- src/odin/service.cc
> Fixed typo so we get german through simple service

- locales/de-DE.json
terminology change to be more road specific
> de-DE updates

- locales/de-DE.json
- locales/en-US.json
- src/odin/narrative_dictionary.cc
- src/odin/narrativebuilder.cc
- test/narrative_dictionary.cc
- test/narrativebuilder.cc
- valhalla/odin/narrative_dictionary.h
- valhalla/odin/narrativebuilder.h
> Updated ‘becomes maneuver’ for guidance g11n

- locales/de-DE.json
noticed some capitalization bugs
> capitalization

- locales/de-DE.json
> es fehlte ein teil des kreisverkehr-texts

- locales/en-US.json
- test/narrative_dictionary.cc
- test/narrativebuilder.cc
This is not the final update for street names.
Discussed with Kevin and we decided to keep it simple for now and get feedback from other language providers before we implement more involved logic.
Closes #266
> Updated the empty_street_name_labels and added tests

- locales/cs-CZ.json
- src/odin/narrative_builder_factory.cc
I created a first version of Czech translation of the phrases (but I’m not sure about the mechanism in `narrative_builder_factory.cc`).
> Add translation into Czech (cs-CZ)

- locales/cs-CZ.json
- locales/de-DE.json
- locales/en-US.json
- src/odin/narrative_dictionary.cc
- src/odin/narrativebuilder.cc
- test/narrative_dictionary.cc
- valhalla/odin/narrative_dictionary.h
- valhalla/odin/narrativebuilder.h
> Refactored to remove unneeded verbal alerts from dictionary

- src/odin/narrative_builder_factory.cc
> Refactored to return NarrativeBuilder pointer by default

- locales/cs-CZ.json
- locales/de-DE.json
- locales/en-US.json
- src/odin/narrative_builder_factory.cc
- src/odin/narrative_dictionary.cc
- src/odin/narrativebuilder.cc
- test/narrative_dictionary.cc
- test/narrativebuilder.cc
- test/util.cc
- valhalla/odin/narrative_dictionary.h
- valhalla/odin/narrativebuilder.h
> Added support for CLDR plural rules

- locales/cs-CZ.json
Translation of the new example_phrases from #310
> Add cs-CZ localization for new example_phrases

- locales/it-IT.json
Locale file translation for Italian.
> it_IT locale

- locales/it-IT.json
Prefer `take <SOMETHING>` to `on <SOMETHING>`.
Fix a number of untranslated phrases.
Fix gender when using 1°, 2°... notation
> IT updates

- src/odin/narrative_dictionary.cc
- src/odin/narrativebuilder.cc
- src/odin/util.cc
- test/narrativebuilder.cc
- test/util.cc
- valhalla/odin/narrative_dictionary.h
- valhalla/odin/util.h
Added std::locale to NarrativeDictionary
Thanks for the locale help @gknisely and @kevinkreiser
> Fixed decimal distance to be locale based.

- src/odin/maneuversbuilder.cc
- valhalla/odin/maneuversbuilder.h
> Added logic to confirm that a maneuver type is set

- src/odin/maneuversbuilder.cc
Closes #327 
```
BEFORE
Make a left U-turn to stay on Aurobindo Marg.
AFTER
Make a right U-turn to stay on Aurobindo Marg.
```
> Fixed invalid u-turn direction

- src/odin/enhancedtrippath.cc
- src/odin/maneuversbuilder.cc
- valhalla/odin/enhancedtrippath.h
- valhalla/odin/maneuversbuilder.h
Closes #192 
``` Diff
< BEFORE
< 2: Turn left onto South Lenola Road/(608). Continue on South Lenola Road.
---
> AFTER
> 2: Bear right.
> 3: Turn left onto South Lenola Road/(608). Continue on South Lenola Road.
```
> Updated to properly call out jughandle routes

- src/odin/maneuversbuilder.cc
- valhalla/odin/maneuversbuilder.h
Closes #225 
``` Diff
< BEFORE
< 2: Take the ramp on the left.
> AFTER
> 2: Take the NY 27 East ramp on the left.
< BEFORE
< 3: Take the ramp on the right. 
> AFTER
> 3: Take the MD 32 East ramp on the right.
```
> Enhanced signless interchange maneuvers to help guide users.

- locales/fr-FR.json
Add french translation for ODIN
> Add french translation

- proto/tripdirections.proto
- src/odin/directionsbuilder.cc
- src/odin/maneuver.cc
- src/odin/maneuversbuilder.cc
- src/odin/transitstop.cc
- test/narrativebuilder.cc
- valhalla/odin/transitstop.h
> Added lat,lon to transit stop in the trip directions

- src/odin/util.cc
- test/narrativebuilder.cc
- test/util_odin.cc
added logic to support timezone abbrev.  example:// 2016-03-29T08:57EDT
> Tz abbrev support

- locales/es-ES.json
I had problems running the tests, as I was asked to make a PR with the files, I did it. Hope it helps.
> translation to Spanish

- locales/en-US-x-pirate.json
thanks @kevinkreiser for suggestions
> Updated some phrases to mix it up

- locales/hi-IN.json
- src/odin/maneuversbuilder.cc
- src/odin/narrative_builder_factory.cc
- src/odin/narrative_dictionary.cc
- src/odin/narrativebuilder.cc
- src/odin/util.cc
- valhalla/odin/narrative_dictionary.h
- valhalla/odin/narrativebuilder.h
Found and fixed a bug - now the proper NarrativeBuilder is created when using language aliases
cc @souperneon @tallytalwar
> Fixed the plural category usage for Hindi

- proto/trippath.proto
- src/odin/enhancedtrippath.cc
- src/odin/maneuversbuilder.cc
- test/maneuversbuilder.cc
- valhalla/odin/enhancedtrippath.h
> Refactored trip path to use an enumerated "Use" instead of individual boolean values

- src/odin/maneuver.cc
- src/odin/narrativebuilder.cc
- src/odin/util.cc
I am doing PRs for the changes I made to make Valhalla more mobile friendly. The changes are based on 1.1.2 release, so there could be some conflicts with the HEAD. Most changes are quite simple to help with discrepancies between C++ compiler/stdlib versions. I added support for compiling Valhalla with either boost::regex (the default) or std::regex (if USE_STD_REGEX preprocessor variable is set). I also abstracted graph storage handling into separate classes by refactoring filesystem based code from baldr GraphTile/GraphReader into abstract GraphTileStorage and GraphTileFsStorage. The storage handling code should perhaps include also write support (that would make mjolnir codebase cleaner), but that is not currently implemented.
> Branch 1.1.2

- locales/hi-IN.json
After listening to the instructions on the app, this sounded odd.
"रास्ते" is a much better usage than "रास्ता". Example: "रास्ते पर दक्षिण की ओर चलें" instead of "रास्ता पर दक्षिण की ओर चलें"
@souperneon Wanna give this a look?
> Fixes some wording in hindi
